=== survone/Static-Code-Analyzer/ped/xml e xsd- PI/tentativa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<tt:schema xmlns:tt="http://www.w3.org/2001/XMLSchema">
    <tt:element name="Tentativa">
        <tt:complexType>
            <tt:sequence>
                
                <tt:element name="user_id"/>
                
                <tt:element name="datetime" type="tt:dateTime"/>
                
                <tt:element name="compilou" type="tt:boolean"/>
                
                <tt:element name="Dict">
                    <tt:complexType>
                        <tt:sequence>
                            <tt:element name="Teste" maxOccurs="unbounded">
                                <tt:complexType>
                                    <tt:sequence>
                                        <tt:element name="Bateria_id" type="tt:integer"/>
                                        <tt:element name="Output" type="tt:string"/>
                                    </tt:sequence>
                                </tt:complexType>
                            </tt:element>
                        </tt:sequence>
                    </tt:complexType>
                </tt:element>

                
    
               <tt:element name="codigoFonte" type="tt:string"/>
    

            </tt:sequence>
        </tt:complexType>
    </tt:element>
</tt:schema>

=== survone/Static-Code-Analyzer/sample_app/data/concursos/contest-3/en-28/user-1/tent-20110113202117/tentativa.xml
<?xm l version="1.0" encoding="UTF-8"?>

<Tentativa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tentativa.xsd">

    <user_id>36</user_id>
    
    <datetime>2010-12-08T16:33:00</datetime>
    
    <compilou>1</compilou>
    
    <Dict>
        <Teste>
            <Teste_id>"13"</Teste_id>
            <Output>0</Output>
        </Teste>
        <Teste>
            <Teste_id>"12"</Teste_id>
            <Output>0</Output>
        </Teste>
        <Teste>
            <Teste_id>"11"</Teste_id>
            <Output>0</Output>
        </Teste>
    </Dict>
    
    <codigoFonte>/lol/cool </codigoFonte>
        
</Tentativa>

=== survone/Static-Code-Analyzer/sample_app/data/concursos/contest-8/en-75/user-1/tent-20110116185528/tentativa.xml
<?xm l version="1.0" encoding="UTF-8"?>

<Tentativa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tentativa.xsd">

    <user_id>36</user_id>
    
    <datetime>2010-12-08T16:33:00</datetime>
    
    <compilou>false</compilou>
    
    <Dict>
        <Teste>
            <Bateria_id>13</Bateria_id>
            <Output>0</Output>
        </Teste>
        <Teste>
            <Bateria_id>12</Bateria_id>
            <Output>0</Output>
        </Teste>
        <Teste>
            <Bateria_id>11</Bateria_id>
            <Output>0</Output>
        </Teste>
    </Dict>
    
    <codigoFonte>sopa.c</codigoFonte>
        
</Tentativa>
