=== survone/Static-Code-Analyzer/documentation/part1/report1/resources/enunciado.xsd
<?xml version="1.0" encoding="UTF-8"?>
<ed:schema xmlns:ed="http://www.w3.org/2001/XMLSchema">
    <ed:element name="Enunciado">
        <ed:complexType>
            <ed:sequence>

                <ed:element name="idConcurso" type="ed:string"/>
                <ed:element name="Peso" default="25">
                    <ed:simpleType>
                        <ed:restriction base="ed:integer">
                            <ed:minInclusive value="0"/>
                            <ed:maxInclusive value="100"/>
                        </ed:restriction>
                    </ed:simpleType>
                </ed:element>
                <ed:element name="Titulo" type="ed:string"/>
                <ed:element name="Descricao" type="ed:string"/>
                <ed:element name="Exemplo" type="ed:string" default="nao existe"/>
                <ed:element name="Docente" type="ed:string" default="unknown"/>
                <ed:element name="FuncAval" type="ed:string"/>

                <ed:element name="Linguagens">
                    <ed:complexType>
                        <ed:sequence>
                            <ed:element name="Linguagem" maxOccurs="unbounded">
                                <ed:simpleType>
                                    <ed:restriction base="ed:string">
                                        <ed:enumeration value="C"/>
                                        <ed:enumeration value="Java"/>
                                        <ed:enumeration value="Haskell"/>
                                    </ed:restriction>
                                </ed:simpleType>
                            </ed:element>
                        </ed:sequence>
                    </ed:complexType>
                </ed:element>
              
                <ed:element name="Dict">
                    <ed:complexType>
                        <ed:sequence>
                            <ed:element name="Teste" maxOccurs="unbounded">
                                <ed:complexType>
                                    <ed:sequence>
                                        <ed:element name="Nome" type="ed:string"/>
                                        <ed:element name="Input" type="ed:string"/>
                                        <ed:element name="Output" type="ed:string"/>
                                    </ed:sequence>
                                </ed:complexType>
                            </ed:element>
                        </ed:sequence>
                    </ed:complexType>
                </ed:element>
            </ed:sequence>
        </ed:complexType>
    </ed:element>
</ed:schema>

=== survone/Static-Code-Analyzer/ped/xml e xsd- PI/enunciado2.xml
<?xm l version="1.0" encoding="UTF-8"?>

<Enunciado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="enunciado.xsd">
    <idConcurso> 1 </idConcurso>
    <Peso>20</Peso>
    <Titulo> Exercicio 2 </Titulo>
    <Descricao> Ordena os n√∫meros por ordem crescente, usando uma lista ligada. </Descricao>
    <Exemplo>Input: 5 4 3 2 1    Output: 1 2 3 4 5</Exemplo>
    <Docente> PRH </Docente>
    <FuncAval>Diff</FuncAval>  
    <Linguagens> 
        <Linguagem>C</Linguagem>        
    </Linguagens>
    <Dict>
        <Teste>
            <Nome>Lista vazia</Nome>
            <Input></Input>
            <Output></Output>
        </Teste>
        <Teste>
            <Nome>Lista c/ 1 elem</Nome>
            <Input>1</Input>
            <Output>1</Output>
        </Teste>
        <Teste>
            <Nome>Lista c/ varios elem</Nome>
            <Input> 8 9 10 2 3 5 6 </Input>
            <Output>2 3 5 6 8 9 10</Output>
        </Teste>
        <Teste>
            <Nome>Lista c/ elem repetidos</Nome>
            <Input> 8 9 10 2 3 5  3 6 8 </Input>
            <Output>2 3 3 5 6 8  8 9 10</Output>
        </Teste>
    </Dict>
        
</Enunciado>

=== survone/Static-Code-Analyzer/sample_app/data/concursos/contest-8/en-75/user-1/tent-20110116185209/enunciado.xml
<?xm l version="1.0" encoding="UTF-8"?>

<Enunciado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="enunciado.xsd">
    <Peso>20</Peso>
    <Titulo> Exercicio 1 </Titulo>
    <Descricao> Some os n√∫meros que lhe sao passados como argumento, e apresente o resultado. </Descricao>
    <Func>Diff</Func>  
    <Linguagens> 
        <Linguagem>C</Linguagem>        
    </Linguagens>
    <Dict>
        <Teste>
            <Nome>Lista vazia</Nome>
            <Input></Input>
            <Output>0</Output>
        </Teste>
        <Teste>
            <Nome>Lista c/ 1 elem</Nome>
            <Input>1</Input>
            <Output>1</Output>
        </Teste>
        <Teste>
            <Nome>Lista c/ varios elem</Nome>
            <Input> 2 3 4 5 </Input>
            <Output>14</Output>
        </Teste>
    </Dict>
        
</Enunciado>
