=== survone/Static-Code-Analyzer/documentation/part4/report/resources/tentativa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<tt:schema xmlns:tt="http://www.w3.org/2001/XMLSchema">
    <tt:element name="Enunciado">
        <tt:complexType>
            <tt:sequence>
                
                
                <tt:element name="idConcurso" type="tt:string"/>
                <tt:element name="idEnunciado" type="tt:string"/>
                <tt:element name="idGrupo"/>
                
                <tt:element name="data" type="tt:date"/>
                <tt:element name="hora" type="tt:time"/>
                
                <tt:element name="compilou" type="tt:integer"/>
                
                <tt:element name="Dict">
                    <tt:complexType>
                        <tt:sequence>
                            <tt:element name="Teste" maxOccurs="unbounded">
                                <tt:complexType>
                                    <tt:sequence>
                                        <tt:element name="Nome" type="tt:string"/>
                                        <tt:element name="Input" type="tt:string"/>
                                        <tt:element name="Output" type="tt:string"/>
                                    </tt:sequence>
                                </tt:complexType>
                            </tt:element>
                        </tt:sequence>
                    </tt:complexType>
                </tt:element>

                <tt:element name="pathMetricas" type="tt:string"/>
                
                <tt:element name="codigoFonte">
                    <tt:complexType>
                        <tt:sequence>
                            <tt:element name="nome" type="tt:string"/>
                            <tt:element name="codigo" type="tt:string"/>
                        </tt:sequence>
                    </tt:complexType>
                </tt:element>

            </tt:sequence>
        </tt:complexType>
    </tt:element>
</tt:schema>

=== survone/Static-Code-Analyzer/TemplateReport/ChapterMod/importdadosFiles/tentativa.xml
<?xm l version="1.0" encoding="UTF-8"?>

<Enunciado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tentativa.xsd">
    <idConcurso>1</idConcurso>
    <idEnunciado>1</idEnunciado>
    <idGrupo>36</idGrupo>
    
    <data>2010-12-08</data>
    <hora>16:33:00</hora>
    
    <compilou>1</compilou>
    
    <Dict>
        <Teste>
            <Nome>Lista vazia</Nome>
            <Input></Input>
            <Output>0</Output>
        </Teste>
        <Teste>
            <Nome>Lista c/ 1 elem</Nome>
            <Input>1</Input>
            <Output>1</Output>
        </Teste>
        <Teste>
            <Nome>Lista c/ varios elem</Nome>
            <Input> 2 3 4 5 </Input>
            <Output>14</Output>
        </Teste>
    </Dict>

    <pathMetricas>sasas</pathMetricas>
    
    <codigoFonte>
        <nome>sopa</nome>
        <codigo>
            <![CDATA[
            #include <stdio.h>
            
            ...restante codigo...
            
            ]]>
        </codigo>
    </codigoFonte>
        
</Enunciado>
